version: '2'
services:
  maindb:
    image: postgres
    environment:
      DB_NAME: maindb
      POSTGRES_USER: maindb
      POSTGRES_PASSWORD: maindb
    ports:
      - 5432:5432

  app:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/code
    ports:
      - "8000:8000"

    depends_on:
      - maindb
